// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-U9iNqx7DgCanPDr5IUnYTwqfO8iEWsk',
    appId: '1:502168568722:web:c32cd89cdb60c8de52b74b',
    messagingSenderId: '502168568722',
    projectId: 'healthprime-2d91a',
    authDomain: 'healthprime-2d91a.firebaseapp.com',
    storageBucket: 'healthprime-2d91a.firebasestorage.app',
    measurementId: 'G-WDWLGH9KMM',
    databaseURL: 'https://healthprime-2d91a-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFM34DA3YgLYlKeGwAuT-VNfvunEXAPTM',
    appId: '1:502168568722:android:e4b21de714a8a3e052b74b',
    messagingSenderId: '502168568722',
    projectId: 'healthprime-2d91a',
    storageBucket: 'healthprime-2d91a.firebasestorage.app',
    databaseURL: 'https://healthprime-2d91a-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUZj6Zp4BKv2LMG1gLKmrMVD6Ea2jJ55U',
    appId: '1:502168568722:ios:821e9dd93fd6870052b74b',
    messagingSenderId: '502168568722',
    projectId: 'healthprime-2d91a',
    storageBucket: 'healthprime-2d91a.firebasestorage.app',
    iosBundleId: 'com.dmkp.healthprime.healthprime',
    databaseURL: 'https://healthprime-2d91a-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUZj6Zp4BKv2LMG1gLKmrMVD6Ea2jJ55U',
    appId: '1:502168568722:ios:821e9dd93fd6870052b74b',
    messagingSenderId: '502168568722',
    projectId: 'healthprime-2d91a',
    storageBucket: 'healthprime-2d91a.firebasestorage.app',
    iosBundleId: 'com.dmkp.healthprime.healthprime',
    databaseURL: 'https://healthprime-2d91a-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-U9iNqx7DgCanPDr5IUnYTwqfO8iEWsk',
    appId: '1:502168568722:web:bc4ef7db72ee5b5852b74b',
    messagingSenderId: '502168568722',
    projectId: 'healthprime-2d91a',
    authDomain: 'healthprime-2d91a.firebaseapp.com',
    storageBucket: 'healthprime-2d91a.firebasestorage.app',
    measurementId: 'G-2E0JN8THLK',
    databaseURL: 'https://healthprime-2d91a-default-rtdb.firebaseio.com',
  );
}
